### ISSUE TITLE
No Active project

### ISSUE THREAD

**Issue by thesemicolonjarvis** [dhirensr/django-scraping#1]
Request Method: | GET
-- | --
http://127.0.0.1:8000/web_interface/search/?q=rubber
2.1.5
ScrapydResponseError
Scrapy 1.5.2 - no active project  Unknown command: list  Use "scrapy" to see available commands

**Comment by dhirensr** [comment]
@thesemicolonjarvis : sorry for the late reply! you need a scrapyd running separately when you run django server

**Comment by dhirensr** [comment]
fixed in https://github.com/dhirensr/django-scraping/commit/c72442d901b1cce3645480a6e06f53b9edf43f37
